
name: Deploy Backend to Render
on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - '.github/workflows/deploy-backend.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "$RENDER_BACKEND_HOOK"
        env:
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
